services:
  flask:
    stdin_open: true
    tty: true
    build:
      context: ../../
      dockerfile: docker/dev/flask.Dockerfile
    env_file:
      - ../../env/dev/.env
    image: twilio-connector-flask-dev:latest
    container_name: twilio-connector-flask-dev
    volumes:
      - ../../app:/app
    ports:
      - "5000:5000"
  
  redis:
    image: redis:7-alpine
    container_name: twilio-connector-redis-dev
    ports:
      - "6379:6379"

